apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  labels:
    app: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: 632715066473.dkr.ecr.us-east-2.amazonaws.com/portfolio-app:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080